# Generated by Django 5.2.14 on 2026-06-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
